# Generated by Django 5.0.6 on 2024-06-21 15:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Supplier ID')),
                ('name', models.CharField(help_text='Unique name of the supplier', max_length=128, unique=True, verbose_name='Supplier Name')),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
